version: '3.8'

services:
  spring-app:
    build: ./fb-ml-module
    ports:
      - "8082:8082"
    depends_on:
      - ai-service
    environment:
      AI_SERVICE_URL: http://ai-service:8000  # Internal Docker network access

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    expose:
      - "8000"
