version: "3"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables file watching inside Docker
      - WATCHPACK_POLLING=true  # Ensures CRA detects file changes
    command: ["npm", "run", "start"]



