version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: modus-mapping-mysql
    restart: always
    environment:
      MYSQL_DATABASE: modus_mapping
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "4306:4306"
    volumes:
      - mysql_data:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    container_name: modus-mapping-graph
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  mysql_data:
  neo4j_data:
